tasks:
  - name: Install, Build & Run
    before: |
      gradle wrapper
    command: |
      echo "Building..."
      ./gradlew bootJar
      echo "Starting application on port 8080..."
      ./gradlew bootRun

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot