tasks:
  - name: Install, Build & Run
    before: |
      # Install JDK
      echo "Installing JDK ..."
      sdk install java 17.0.4.1-tem < /dev/null
      ./gradlew bootJar
    command: |
      echo "Starting application..."
      ./gradlew bootRun

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot